name: Silver Tracker (5 Min)

on:
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # required for git push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run silver tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python silver_tracker.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add silver_history.csv nifty_bt_cache.json nifty_indices_history.csv

          git commit -m "Update silver history" || echo "No changes to commit"

          git push
